### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by lakano**
# Fixes \#

## Type (Highlight the corresponding type)
- Bugfix
- **Feature**
- Documentation
- Refactoring (e.g. Style updates, Test implementation, etc.)
- Other (please describe):

## Checklist
- [X] Code updated to current masters head
- [X] Passes CI checks
- [ ] Is a part of an issue
- [ ] Tests added for the bugfix or newly implemented feature, describe below why if not
- [X] Changelog is updated
- [ ] Documentation of code and features exists

## Changes
- Add french translations
- 
- 
- 
-

### CODE REVIEW

**Comment by lakano** [comment]
I've made a mistake with my pull requests ( another commits mixed in ). I'm closing this pull request and I'll re-open an new one.

**Comment by SamuelWei** [comment]
@lakano Thank you! You are welcome to open another PR or add the french translation to our translation system if you prefer: https://poeditor.com/join/project/UGpZY4JAnz

**Comment by lakano** [comment]
@SamuelWei Few minutes ago you give me a POEditor « https://poeditor.com/projects/view?id=700042 » on the issue https://github.com/THM-Health/PILOS/discussions/486#discussioncomment-10145679 and this one return a 404. 

Then I saw this previous comment you did on my PR of the last year, this POEditor link works, but it's 100% complete and seems to be related only to v2/v3. There is another link for v4 ? If not, what is the best way to complete the missing french translations please ?

**Comment by lakano** [comment]
Just got the POEditor notification that you've added the v4, I'll start to translate :)

**Comment by lakano** [comment]
@SamuelWei I've finished to translate 100% of v4 on POEditor. 
Is it possible that you run the necessary to be converted to the develop branch please?

**Pull request closed without merging**
